version: "3.8"

services:

  payd:
    restart: always
    container_name: payd
    image: electrumsv/payd:develop
    ports:
      - "9999:9999"
      - "8332:8332"  # node-api server (to replace bitcoind JSON-RPC)
    environment:
      NODEAPI_HOST: 0.0.0.0
      NODEAPI_PORT: 8332
      RESTAPI_HOST: 0.0.0.0
      WALLET_PASSWORD: "pass"
    volumes:
      - ./payd-data:/root/.electrum-sv
    entrypoint: "/bin/sh /root/.electrum-sv/load_wallet.sh"
