version: "3.8"

services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./regtest/create_mapi_user.sh:/docker-entrypoint-initdb.d/create_mapi_user.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=mapimaster
      - POSTGRES_PASSWORD=mapimasterpass
    stdin_open: true
    tty: true

  node:
    # Note. The blockchains/blockchain_115_3677f4 regtest blockchain is loaded on startup and
    # one additional block is mined to take the node out of initial block download mode. Otherwise
    # it will not respond to p2p protocol requests for getblocks etc. nor will it publish
    # notifications to ZMQ subscribers.
    # See: ./node/server.py for the initial startup script
    container_name: node
    build:
      context: ./regtest
      dockerfile: ./node/Dockerfile
    ports:
      - "18332:18332"
      - "18444:18444"

  whatsonchain:
    container_name: whatsonchain
    build:
      context: ./regtest
      dockerfile: ./whatsonchain/Dockerfile
    ports:
      - "55555:3002"
    environment:
      ELECTRUMX_HOST: "host.docker.internal"
      ELECTRUMX_PORT: 51001
      RPC_HOST: "host.docker.internal"
      RPC_PORT: 18332
      RPC_USERNAME: rpcuser
      RPC_PASSWORD: rpcpassword

  # ElectrumX is only used by Whatsonchain in this stack - ElectrumSV has removed it as a dependency in v1.4.x
  electrumx:
    container_name: electrumx
    build:
      context: ./regtest
      dockerfile: ./electrumx/Dockerfile
    ports:
      - "51001:51001"
    environment:
      DAEMON_URL: "http://rpcuser:rpcpassword@host.docker.internal:18332"
      ELECTRUMX_PORT: 51001
      PYTHONUNBUFFERED: 1
      SERVICES: tcp://:51001
      DB_DIRECTORY: /opt/data
      DB_ENGINE: leveldb
      COIN: BitcoinSV
      COST_SOFT_LIMIT": 0
      COST_HARD_LIMIT": 0
      MAX_SEND: 10000000
      LOG_LEVEL: debug
      NET: regtest
      ALLOW_ROOT: 1

  electrumsv:
    container_name: electrumsv
    depends_on:
      - "simple_indexer"
      - "reference_server"
    build:
      context: ./regtest
      dockerfile: ./electrumsv/Dockerfile
    ports:
      - "9999:9999"
      - "8332:8332"  # node-api server (to replace bitcoind JSON-RPC)
    environment:
      NODEAPI_HOST: "0.0.0.0"
      NODEAPI_PORT: 8332
      BITCOIN_NODE_HOST: host.docker.internal
      BITCOIN_NODE_PORT: 18332
      BITCOIN_NODE_RPCUSER: rpcuser
      BITCOIN_NODE_RPCPASSWORD: rpcpassword
      RESTAPI_HOST: "0.0.0.0"

  reference_server:
    container_name: reference_server
    depends_on:
      - "header_sv"
      - "simple_indexer"
    build:
      context: ./regtest
      dockerfile: ./reference_server/Dockerfile
    ports:
      - "47124:47124"
      - "47126:47126"
    environment:
      SKIP_DOTENV_FILE: 1  # Allows us to overrride all of the defaults in the .env file
      EXTERNAL_HOST: "0.0.0.0"
      EXTERNAL_PORT: 47124
      INTERNAL_HOST: "0.0.0.0"
      INTERNAL_PORT: 47126
      EXPOSE_HEADER_SV_APIS: 1
      HEADER_SV_URL: 'http://host.docker.internal:33444'
      EXPOSE_PAYMAIL_APIS: 1
      EXPOSE_INDEXER_APIS: 1
      INDEXER_URL: 'http://host.docker.internal:49241'
      NOTIFICATION_TEXT_NEW_MESSAGE: New message arrived
      MAX_MESSAGE_CONTENT_LENGTH: 65536
      CHUNKED_BUFFER_SIZE: 1024
      NETWORK: regtest
      ENABLE_OUTBOUND_DATA_DELIVERY: 1
    command:
      sh -c 'python3 /reference_server/server.py'

  simple_indexer:
    container_name: simple_indexer
    build:
      context: ./regtest
      dockerfile: ./simple_indexer/Dockerfile
    ports:
      - "49241:49241"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: 49241
      REFERENCE_SERVER_HOST: "host.docker.internal"
      REFERENCE_SERVER_PORT: 47124
      REFERENCE_SERVER_SCHEME: http
      BITCOIN_NODE_HOST: "host.docker.internal"
      BITCOIN_NODE_PORT: 18332
      BITCOIN_NODE_RPCUSER: rpcuser
      BITCOIN_NODE_RPCPASSWORD: rpcpassword
      SIMPLE_INDEX_RESET: 1
    command:
      sh -c 'python3 /simple_indexer/server.py'

  dpp_proxy:
    container_name: dpp_proxy
    build:
      context: ./regtest
      dockerfile: ./dpp_proxy/Dockerfile
    ports:
      - "8445:8445"
    environment:
      SERVER_HOST: 127.0.0.1
      SERVER_FQDN: "127.0.0.1:8445"
      SERVER_PORT: ":8445"
      TRANSPORT_MODE: hybrid
      LOG_LEVEL: debug
    command:
      sh -c '/opt/build/release/server'

  header_sv:
    container_name: header_sv
    build:
      context: ./regtest
      dockerfile: ./header_sv/Dockerfile
    ports:
      - "33444:33444"
    environment:
      SPRING_PROFILES_ACTIVE: bsv-regtest
      SERVER_PORT: 33444
      SERVER_ADDRESS: 0.0.0.0
      HEADERSV_NETWORK_MINPEERS: 1
      HEADERSV_NETWORK_MAXPEERS: 1
      HEADERSV_NETWORK_PEERS: host.docker.internal
      HEADERSV_NETWORK_PORT: 18444
      HEADERSV_NETWORK_DISCOVERYENABLED: 'true'
      HEADERSV_NETWORK_INITIALCONNECTIONS: host.docker.internal:18444
      HEADERSV_NETWORK_GENESISHEADERHEX: 0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4adae5494dffff7f2002000000

    command:
      sh -c '/app/app-boot-2.0.2/bin/app'

  merchant_api:
    container_name: merchant_api
    depends_on:
      - "postgres"
    build:
      context: ./regtest
      dockerfile: ./merchant_api/Dockerfile
    ports:
      - "5050:5050"
    environment:
      ASPNETCORE_ENVIRONMENT: PRODUCTION
      ASPNETCORE_Kestrel__Certificates__Default__Password: YourSecurePassword
      ASPNETCORE_Kestrel__Certificates__Default__Path:
      ASPNETCORE_URLS: http://0.0.0.0:5050
      ConnectionStrings__DBConnectionString: "Server=host.docker.internal;Port=5432;UserId=mapi_crud;Password=merchant;Database=merchant_gateway;"
      ConnectionStrings__DBConnectionStringDDL: "Server=host.docker.internal;Port=5432;User Id=merchantddl;Password=merchant;Database=merchant_gateway;"
      ConnectionStrings__DBConnectionStringMaster: "Server=host.docker.internal;Port=5432;User Id=mapimaster;Password=mapimasterpass;Database=merchant_gateway;"
      AppSettings__QuoteExpiryMinutes: 10
      AppSettings__CallbackIPAddresses:
      AppSettings__ZmqConnectionTestIntervalSec: 60
      AppSettings__RestAdminAPIKey: apikey
      AppSettings__DeltaBlockHeightForDoubleSpendCheck: 144
      AppSettings__CleanUpTxAfterDays: 3
      AppSettings__CleanUpTxPeriodSec: 3600
      AppSettings__WifPrivateKey: Kz4oGtUm2jbJGmDVHgUxgMppaXNUbcfR3myHxvjVWm7zhrCK3LdW
      AppSettings__Notification__NotificationIntervalSec: 60
      AppSettings__Notification__InstantNotificationsTasks: 2
      AppSettings__Notification__InstantNotificationsQueueSize: 1000
      AppSettings__Notification__MaxNotificationsInBatch: 100
      AppSettings__Notification__SlowHostThresholdInMs: 1000
      AppSettings__Notification__InstantNotificationsSlowTaskPercentage: 20
      AppSettings__Notification__NoOfSavedExecutionTimes: 10
      AppSettings__Notification__NotificationsRetryCount: 10
      AppSettings__Notification__SlowHostResponseTimeoutMS: 1000
      AppSettings__Notification__FastHostResponseTimeoutMS: 2000
      AppSettings__MinerIdServer__Url:
      AppSettings__MinerIdServer__Alias:
      AppSettings__MinerIdServer__Authentication:
      AppSettings__CheckFeeDisabled: 'false'
      AppSettings__DSHostBanTimeSec: 1000
      AppSettings__DSMaxNumOfTxQueries: 100000
      AppSettings__DSCachedTxRequestsCooldownPeriodSec: 1
      AppSettings__DSMaxNumOfUnknownTxQueries: 100000
      AppSettings__DSUnknownTxQueryCooldownPeriodSec: 1
      AppSettings__DSScriptValidationTimeoutSec: 1
      AppSettings__EnableHTTP: 'true'
      AppSettings__DontParseBlocks: 'true'
      AppSettings__DontInsertTransactions: 'true'
    command:
      sh -c 'dotnet /app/publish/MerchantAPI.APIGateway.Rest.dll'
